# The URL the site will be built for
base_url = "https://mjolner.tech"

title = "mjolner.tech"
description = "Freelance Software Engineer"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "ando_cv"

[markdown.highlighting]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
theme = "everforest-light"

[extra]
# Put all your custom variables here
hyde_theme = "theme-base-0d"

[[extra.navigation]]
url = "/"
name = "Home"
title = "Front Page"

[[extra.navigation]]
url = "/about"
name = "About"
title = "About"

[[extra.navigation]]
url ="/resume"
name = "Resume"
title = "Resume"

[[extra.navigation]]
url = "https://blog.mjolner.tech/"
name = "Blog"
title = "Blog"

[[extra.navigation]]
url = "https://www.linkedin.com/in/divinegod/"
name = "LinkedIn"
title = "LinkedIn Account"

[[extra.navigation]]
url = "https://github.com/divinegod/"
name = "GitHub"
title = "Github Account"

[[extra.navigation]]
url = "https://aus.social/@voided"
name = "@voided"
title = "Fediverse Account"
